name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches:
      - main  # Chạy pipeline khi có thay đổi trên nhánh "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23' # Chọn phiên bản Node.js phù hợp

      # Step 3: Install dependencies and build project
      - name: Install dependencies
        run: |
          npm install
          npm run build

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # Step 5: Upload build files to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://alothy.com --delete

      # Step 6: Invalidate CloudFront cache
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id E36JTKORD9DI4H --paths "/*"
